mixture: 
    max_feature_dim: 100 #100 # 240 #240 #500 #100
    max_model_dim: 100 #100 #240
    inflate_full: False
    gmm:
        max_feature_dim: 100 #100 #240 #240 #500 #100
        max_model_dim: 100 #240
        max_num_cluster: 5
        max_mean: 5
        max_var: 5
        inflate_full: False
        diversity: 5  # for each dim in [2, max_feature_dim], we generate 'diversity' number of them
        percentile: 0.9
        data_dir: 'syn_data/MIXTURE'

    scm_prob:
        max_feature_dim: 100
        min_num_layer: 3
        max_num_layer: 7
        min_hidden_size: 20
        max_hidden_size: 40
        alpha: 1.5
        beta: 4.0
        data_dir: 'syn_data/MIXTURE'

    scm_contextual:
        max_feature_dim: 100
        min_num_layer: 3
        max_num_layer: 7
        min_hidden_size: 20
        max_hidden_size: 40
        alpha: 1.5
        beta: 4.0
        data_dir: 'syn_data/MIXTURE'

    corpula:
        max_feature_dim: 100

    density:
        max_feature_dim: 100 #100 #240 #240 #100
        n_numeric: 100
        data_dir: 'syn_data/MIXTURE'
